######################################
# This script defines the project pipeline -
# it specifies the execution orders for all the code in this
# repo using a series of actions.
######################################

version: '5.0'

actions:

  generate_dataset_table:
    run: ehrql:dev generate-dataset analysis/define_dataset_table.py
      --output output/data/dataset_table_no_region.csv
    outputs:
      highly_sensitive:
        cohort: output/data/dataset_table_no_region.csv

  map_dataset_table:
    run: python:v2 analysis/map_region.py
      --file-type dataset
      --src-path output/data/dataset_table_no_region.csv
      --dest-path output/data/dataset_table.csv
    needs: [generate_dataset_table]
    outputs:
      highly_sensitive:
        cohort: output/data/dataset_table.csv

  generate_dataset_missing:
    run: ehrql:dev generate-dataset analysis/define_dataset_missing.py
      --output output/data/dataset_missing.csv
    outputs:
      highly_sensitive:
        cohort: output/data/dataset_missing.csv

  # Check missing sex values
  missing:
    run: r:v1 analysis/descriptive/sex_age_missing.R
    needs: [generate_dataset_missing]
    outputs:
      moderately_sensitive:
        table: output/tables/cohort_sex_age_missing.csv

  # Measures - prevalent and new prescribing - overall
  measures_overall:
    run: ehrql:dev generate-measures analysis/measures_overall.py
      --output output/measures/measures_overall.csv
      --
      --start-date "2018-01-01"
      --intervals 54
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_overall.csv

  # Measures - prevalent prescribing - by demographic categories
  measures_demo_prev:
    run: ehrql:dev generate-measures analysis/measures_demo_prev.py
      --output output/measures/measures_demo_prev_no_region.csv
      --
      --start-date "2018-01-01"
      --intervals 54
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_demo_prev_no_region.csv

  map_measures_demo_prev:
    run: python:v2 analysis/map_region.py
      --file-type measure
      --src-path output/measures/measures_demo_prev_no_region.csv
      --dest-path output/measures/measures_demo_prev.csv
    needs: [measures_demo_prev]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_demo_prev.csv

  # Measures - new prescribing - by demographic categories
  measures_demo_new:
    run: ehrql:dev generate-measures analysis/measures_demo_new.py
      --output output/measures/measures_demo_new_no_region.csv
      --
      --start-date "2018-01-01"
      --intervals 54
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_demo_new_no_region.csv

  map_measures_demo_new:
    run: python:v2 analysis/map_region.py
      --file-type measure
      --src-path output/measures/measures_demo_new_no_region.csv
      --dest-path output/measures/measures_demo_new.csv
    needs: [measures_demo_new]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_demo_new.csv

  # Measures - prevalent prescribing - by opioid type
  measures_type:
    run: ehrql:dev generate-measures analysis/measures_type.py
      --output output/measures/measures_type.csv
      --
      --start-date "2018-01-01"
      --intervals 54
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_type.csv

  # Measures - prevalent and new prescribing - in people in care home
  measures_carehome:
    run: ehrql:dev generate-measures analysis/measures_carehome.py
      --output output/measures/measures_carehome.csv
      --
      --start-date "2018-01-01"
      --intervals 54
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_carehome.csv

  ## Process time series data - overall prescribing
  process_ts_overall:
   run: r:v1 analysis/process/process_ts_overall.R
   needs: [measures_overall]
   outputs:
      moderately_sensitive:
        timeseries_csv: output/timeseries/ts_overall*.csv

  ## Process time series data - prescribing by demographics
  process_ts_demo:
   run: r:v1 analysis/process/process_ts_demo.R
   needs: [map_measures_demo_prev, map_measures_demo_new]
   outputs:
      moderately_sensitive:
        timeseries_csv: output/timeseries/ts_demo*.csv

  ## Process time series data - prescribing by admin route
  process_ts_type:
   run: r:v1 analysis/process/process_ts_type.R
   needs: [measures_type]
   outputs:
      moderately_sensitive:
        timeseries_csv: output/timeseries/ts_type*.csv

  ## Process time series data - prescribing to people in carehome
  process_ts_carehome:
   run: r:v1 analysis/process/process_ts_carehome.R
   needs: [measures_carehome]
   outputs:
      moderately_sensitive:
        timeseries_csv: output/timeseries/ts_carehome*.csv

  ## Check time series
  figures_ts:
    run: r:v1 analysis/descriptive/ts_figures.R
    needs: [process_ts_overall, process_ts_type, process_ts_carehome, process_ts_demo]
    outputs:
      moderately_sensitive:
        plots: output/descriptive/ts_plot*.png

  ## Results table
  table:
    run: r:v1 analysis/descriptive/table_stand.R
    needs: [map_dataset_table]
    outputs:
      moderately_sensitive:
        table: output/tables/table_*.csv
